---
- name: Implementar el index.html "Hola Mundo"
  template:
    src: ../templates/index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  notify: Restart Apache